### ISSUE TITLE
Nothing is happening when watching a Blazor WASM project

### ISSUE THREAD

**Issue by IneedHelp** [MONQDL/DartSassBuildWatcherTool#5]
Hello, I tried using `dsbw --watch path_to_project` and while the tool does detect file changes and renames the file to some temp file name, it doesn't compile anything, or at least it doesn't create the CSS file next to the SCSS file. Am I doing something wrong?

**Comment by aligin** [comment]
Hello. Try to add `--dir path_to_project`. The options `--files` and `--dir` configures where the tool will locate and compile scss files, while the `--watch` option only triggers the builder to compile files from directories or files from --dir and --files options.

I agree it's not obvious, I'll add some notes to the documentation.

**Comment by IneedHelp** [comment]
When I use `--dir` I get an error

```
During compilation of SCSS code an error occurred. See details:

Message: During Compilation of Sass code by using the Sass compiler a JavaScript error has occurred:

TypeError: S.GetCurrentDirectory is not a function
   at L (DartSassHost.Resources.sass-bundled.min.js:4074:3) -> S.GetCurrentDirectory();this._fileExistenceCache=new Map;this._fileContentCache=new Map;this.support…
   at aa (DartSassHost.Resources.sass-bundled.min.js:4081:88)
   at X.compileFile (DartSassHost.Resources.sass-bundled.min.js:4084:33)
   at Script [3]:1:12
Description: TypeError: S.GetCurrentDirectory is not a function
   at L (DartSassHost.Resources.sass-bundled.min.js:4074:3) -> S.GetCurrentDirectory();this._fileExistenceCache=new Map;this._fileContentCache=new Map;this.support…
   at aa (DartSassHost.Resources.sass-bundled.min.js:4081:88)
   at X.compileFile (DartSassHost.Resources.sass-bundled.min.js:4084:33)
   at Script [3]:1:12
   ```

   The DartSassBuilder builds .scss files just fine, so I don't know what causes this.

**Comment by aligin** [comment]
There was a bug in 1.0.2. Use 1.0.3.

**Comment by IneedHelp** [comment]
Thank you! Works great.

_sorry for the late reply_
